// new exercise object
export const ADD_NEW_EXERCISE_TYPE= "ADD_NEW_EXERCISE_TYPE";
export const ADD_NEW_EXERCISE_QUES= "ADD_NEW_EXERCISE_QUES";
export const ADD_NEW_EXERCISE_ID  = "ADD_NEW_EXERCISE_ID";

// exercises array
export const ADD_NEW_EXERCISE= "ADD_NEW_EXERCISE";
export const ADD_SCORE_TIME= "ADD_SCORE_TIME";
export const EDIT_EXERCISE= "EDIT_EXERCISE";
export const SET_ALL_EXERCISES= "SET_ALL_EXERCISES";
export const REMOVE_EXERCISE= "REMOVE_EXERCISE";
export const INCREMENT_ID= "INCREMENT_ID";
export const SET_COUNTER= "SET_COUNTER";

// isHost
export const IS_HOST="IS_HOST";
export const IS_SHARED="IS_SHARED";
export const ADD_SHARED_EXERCISE="ADD_SHARED_EXERCISE";
export const GET_SHARED_EXERCISES= "GET_SHARED_EXERCISE";
export const REMOVE_SHARED_EXERCISE="REMOVE_SHARED_EXERCISE";
export const ADD_USER="ADD_USER";
export const REMOVE_USER="REMOVE_USER";
export const ADD_SHARED_RESULT="ADD_SHARED_RESULT";


// Sugarizer
export const SET_USER="SET_USER";



